[features]
seeds = false
skip-lint = false
[programs.localnet]
stake_my_sol = "FmziXL4yqAoj6taTrpxQm4JGQn4tFiXX7CPhrm2Bieun"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "testnet"
cluster = "devnet"
wallet = "/home/nick/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
